export enum ColorEnum {
    RED = 'Red',
    BLUE = 'Blue',
    GREEN = 'Green',
    YELLOW = 'Yellow',
    ORANGE = 'Orange',
    PURPLE = 'Purple',
    PINK = 'Pink',
    BROWN = 'Brown',
    BLACK = 'Black',
    WHITE = 'White',
    GRAY = 'Gray',
    BEIGE = 'Beige',
    IVORY = 'Ivory',
    TEAL = 'Teal',
    TURQUOISE = 'Turquoise',
    LIME = 'Lime',
    OLIVE = 'Olive',
    MAROON = 'Maroon',
    NAVY = 'Navy',
    INDIGO = 'Indigo',
    GOLD = 'Gold',
    SILVER = 'Silver',
    BRONZE = 'Bronze',
    CORAL = 'Coral',
    SALMON = 'Salmon',
    MINT = 'Mint',
    LAVENDER = 'Lavender',
    CHARCOAL = 'Charcoal',
    PEACH = 'Peach',
    MUSTARD = 'Mustard',
    SAND = 'Sand',
    SKY = 'Sky',
    PLUM = 'Plum',
    EMERALD = 'Emerald',
    RUBY = 'Ruby',
    SAPPHIRE = 'Sapphire'
}

export enum SizeEnum {
    // Geyim ölçüləri
    XS = 'XS',
    S = 'S',
    M = 'M',
    L = 'L',
    XL = 'XL',
    XXL = 'XXL',
    XXXL = 'XXXL',

    // Əlavə ölçülər (unisex və ya uşaqlar üçün)
    XXS = 'XXS',
    XXXS = 'XXXS',

    // Ayaqqabı ölçüləri (EU standartı)
    EU36 = 'EU 36',
    EU37 = 'EU 37',
    EU38 = 'EU 38',
    EU39 = 'EU 39',
    EU40 = 'EU 40',
    EU41 = 'EU 41',
    EU42 = 'EU 42',
    EU43 = 'EU 43',
    EU44 = 'EU 44',
    EU45 = 'EU 45',
    EU46 = 'EU 46',
    EU47 = 'EU 47',
}
